apiVersion: v1
kind: Service
metadata:
  name: bluegreen-service
spec:
  selector:
    app: blue-app  # Change to "green-app" for switching
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
